"""Initial migration: User and ClaimedBandName models

Revision ID: 3e38e81e8a83
Revises: 
Create Date: 2026-01-13 16:35:40.605380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e38e81e8a83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('claimed_band_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('band_name', sa.String(length=100), nullable=False),
    sa.Column('band_name_lower', sa.String(length=100), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claimed_band_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claimed_band_names_band_name_lower'), ['band_name_lower'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claimed_band_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claimed_band_names_band_name_lower'))

    op.drop_table('claimed_band_names')
    op.drop_table('users')
    # ### end Alembic commands ###
